version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

image: &image
  docker:
    - image: cimg/node:20.19.0
  resource_class: medium+

setup: &setup
  - run:
      name: Setup
      command: |
        sudo npm install -g pnpm@10.13.1
        pnpm install

jobs:
  test:
    <<: *image
    steps:
      - checkout
      - <<: *setup
      - run:
          name: Audit
          command: pnpm audit || exit 0
      - run:
          name: Test
          command: pnpm --if-present lint && pnpm --if-present ts:check && pnpm --if-present test
  build-test:
    <<: *image
    steps:
      - checkout
      - <<: *setup
      - run:
          name: Audit
          command: pnpm audit || exit 0
      - run:
          name: Test
          command: |
            pnpm --aggregate-output --color $(node latest-pnpm-filters.cjs) lint
            pnpm --aggregate-output --color $(node latest-pnpm-filters.cjs) ts:check
            pnpm --aggregate-output --color $(node latest-pnpm-filters.cjs) test
  build:
    <<: *image
    steps:
      - checkout
      - <<: *setup
      - run:
          name: Build
          command: pnpm --aggregate-output --color $(node latest-pnpm-filters.cjs) build
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Sync built folders to S3
          command: |
            S3_BASE_PATH="s3://$S3_ASSETS_BUCKET/team/fe-static-apps"

            for dir in dist/*; do
              if [ -d "$dir" ]; then
                folder_name=$(basename "$dir")
                echo "Syncing $folder_name..."
                aws s3 sync "$dir" "$S3_BASE_PATH/$folder_name/<< pipeline.git.tag >>" --delete --exact-timestamps
              else
                echo "Skipping $dir as it is not a directory."
              fi
            done

workflows:
  run-tests:
    jobs:
      - test:
          context: commercelayer
          filters:
            tags:
              ignore: /v.*|pr-.*/

  test-build-and-push:
    jobs:
      - build-test:
          context: commercelayer
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - build-test
          context: commercelayer
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
            branches:
              ignore: /.*/
